# Generated by Django 4.2.1 on 2023-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="semester", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="session", name="type", field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="course", unique_together={("tag", "semester")},
        ),
    ]
