# Generated by Django 4.2.1 on 2023-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0002_remove_coursecombo_units_remove_schedule_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecombo",
            name="schedules",
            field=models.ManyToManyField(
                related_name="course_combos", to="optimizer.schedule"
            ),
        ),
    ]
