# Generated by Django 4.2.1 on 2023-05-19 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("optimizer", "0002_alter_course_semester_alter_session_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="optimizer.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="optimizer.course",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions_taught",
                to="optimizer.professor",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="time",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time",
                to="optimizer.time",
            ),
        ),
    ]
