# Generated by Django 4.2.1 on 2023-07-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0003_alter_coursecombo_schedules"),
    ]

    operations = [
        migrations.RemoveField(model_name="coursecombo", name="course",),
        migrations.RemoveField(model_name="coursecombo", name="schedules",),
        migrations.RemoveField(model_name="coursecombo", name="sessions",),
        migrations.RemoveField(model_name="coursecombo", name="times",),
        migrations.RemoveField(model_name="session", name="course",),
        migrations.RemoveField(model_name="session", name="professor",),
        migrations.RemoveField(model_name="session", name="time",),
        migrations.AddField(
            model_name="schedule",
            name="course_data",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(name="Course",),
        migrations.DeleteModel(name="CourseCombo",),
        migrations.DeleteModel(name="Session",),
        migrations.DeleteModel(name="Time",),
    ]
