# Generated by Django 4.2.1 on 2023-05-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0003_alter_course_schedule_alter_schedule_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="difficulty",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="professor",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.CreateModel(
            name="CourseCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_combos",
                        to="optimizer.course",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_combos",
                        to="optimizer.schedule",
                    ),
                ),
                ("sessions", models.ManyToManyField(to="optimizer.session")),
                ("times", models.ManyToManyField(to="optimizer.time")),
            ],
        ),
    ]
