# Generated by Django 4.2.1 on 2023-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0004_remove_coursecombo_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="course_data",
            field=models.CharField(default=[], max_length=10000),
            preserve_default=False,
        ),
    ]
