# Generated by Django 4.2.1 on 2023-07-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0006_alter_schedule_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="semester",
            field=models.CharField(default=20231, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="units",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
